# -*- coding: utf-8 -*-
"""
Step_01_Extract_Params_from_experimental_data.py

Extracts calibration parameters (background fraction f_bg, bunching
pedestal A2) from the corrected experimental files produced by Step_00,
and pools them into per-emitter-number statistics used to calibrate the
synthetic data generated by Step_02.

For each file:
  1. Loads the last (longest-integration, best signal-to-noise) iteration
     column, plus its raw-counts companion file if available (for proper
     Poisson-weighted fitting).
  2. Fits the same 3-parameter g2(t) model used throughout this pipeline
     (see the MODEL section below for why there is no tau2 term), falling
     back to a direct window average if the fit does not converge.
  3. Inverts the N-emitter dilution relation to recover a background
     fraction f_bg specific to that file.

Results are pooled per emitter number (N=1 on its own; N=2..5 pooled
together, since N=3-5 individually have too few real files to
characterize alone), with a low-confidence flag and a cascading fallback
to blend in N=1 data when even the pooled N>=2 group is too small.

Outputs `experimental_calibration.csv` (one row per file) and
`calibration_summary.csv` (pooled statistics), both consumed by Step_02.
"""

import numpy as np
import pandas as pd
import os
import re
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

# =========================================================
# CONFIG
# =========================================================
FOLDER = "Experimental_Data"
PLOT_DEBUG = True   # Set False if too many plots

# Files are expected in the SAME multi-column format as the simulated data:
# a "tau" column plus one "iter_" column per accumulated integration step
# (e.g. exp_g2_raw_rep_1_n1.csv with columns tau, iter_1, iter_2, ..., iter_9).
# Only the LAST iter_ column (longest integration time / most converged
# estimate) is used - see the note in `load_experimental_file` below for why.
FILENAME_PATTERN = re.compile(r"rep_(\d+)_n(\d+)\.csv$")

# Below this many independent files for a given pool, flag the resulting
# statistics as low-confidence rather than silently reporting a mean/std
# that looks just as authoritative as a well-sampled pool.
MIN_SAMPLES_FOR_CONFIDENCE = 10

# =========================================================
# MODEL
# =========================================================
# The emitters studied here are driven at high excitation power, which
# produces bunching that only decays back to baseline on a microsecond
# timescale - many orders of magnitude slower than the +/-100ns
# measurement window. Within that window, this bunching is therefore
# indistinguishable from a constant elevation rather than a resolvable
# decay. Two modeling choices follow directly from this:
#
#   1. tau2 is dropped entirely. A2 is a free constant pedestal
#      (equivalent to tau2 -> infinity), rather than a decaying term with
#      an unconstrainable timescale.
#   2. offset is fixed at 1.0, not fit. The instrument's own long-
#      timescale normalization already establishes the true baseline;
#      re-deriving a baseline from within the +/-100ns window itself would
#      measure a bunching level that has not yet finished decaying,
#      biasing every extracted g2(0) downward.
def g2_model(t, A1, tau1, A2):
    t = np.abs(t)
    return 1.0 - A1*np.exp(-t/tau1) + A2

def fit_g2(tau, g2, sigma=None):
    """
    If sigma is given, performs a Poisson-weighted least-squares fit
    (bins with fewer real counts are noisier and are correctly given less
    influence on the fit), using sigma = sqrt(raw_counts)/baseline derived
    from Step_00's companion "_rawcounts.csv" file. Falls back to an
    unweighted fit if no companion file is found for this repetition.
    """
    mask = np.isfinite(g2)
    tau = tau[mask]
    g2 = g2[mask]
    sigma = sigma[mask] if sigma is not None else None

    if len(g2) < 10:
        return None

    A1_guess = 1 - np.min(g2)
    tau1_guess = 0.5
    A2_guess = max(0, np.max(g2) - 1)

    p0 = [A1_guess, tau1_guess, A2_guess]
    bounds = ([0, 0.01, 0], [2, 15, 2])

    try:
        if sigma is not None:
            popt, _ = curve_fit(g2_model, tau, g2, p0=p0, bounds=bounds,
                                  sigma=sigma, absolute_sigma=True, maxfev=20000)
        else:
            popt, _ = curve_fit(g2_model, tau, g2, p0=p0, bounds=bounds, maxfev=20000)
        return popt
    except Exception:
        return None

# =========================================================
# ROBUST g2(0) EXTRACTION
# =========================================================
def estimate_g2_zero(tau, g2, sigma=None):
    """
    Returns (g2_0, method, popt). popt (A1, tau1, A2) is only returned when
    the fit both converged AND produced a physically valid g2_0.

    A2 is a directly meaningful, constant bunching pedestal - but since no
    decay time can be resolved for it from this narrow a window, there is
    no tau2 to report or use downstream (see Step_02 for how this is
    handled there).
    """
    center_mask = np.abs(tau) < 1.0
    if np.sum(center_mask) > 3:
        g2_direct = np.mean(g2[center_mask])
    else:
        g2_direct = np.min(g2)

    popt = fit_g2(tau, g2, sigma=sigma)

    if popt is not None:
        A1, tau1, A2 = popt
        g2_fit = 1.0 - A1 + A2
    else:
        g2_fit = None

    if g2_fit is not None and 0 <= g2_fit <= 2:
        return g2_fit, "fit", popt
    else:
        return g2_direct, "direct", None

# =========================================================
# BACKGROUND + BUNCHING EXTRACTION
# =========================================================
def extract_background_fraction(tau, counts, n_emitters, raw_counts=None, baseline=None):
    """
    Returns (f_bg, method, g2_0, popt).

    counts is already the normalized g2(tau) (trusting Step_0's baseline -
    see MODEL note above). If raw_counts and baseline are also given (from
    a companion "_rawcounts.csv" file), the fit is properly Poisson-
    weighted: sigma = sqrt(raw_counts)/baseline. Falls back to unweighted
    if no companion file was found for this repetition.
    """
    if len(tau) < 10:
        return None, "bad_baseline", None, None

    g2 = counts  # already normalized by Step_0 - use as-is

    sigma = None
    if raw_counts is not None and baseline is not None and baseline > 0:
        sigma = np.sqrt(np.maximum(raw_counts, 1)) / baseline

    g2_0, method, popt = estimate_g2_zero(tau, g2, sigma=sigma)

    if g2_0 < -0.2 or g2_0 > 1.0:
        # The dilution formula below (N emitters diluted by uncorrelated
        # background) is only physically meaningful for g2_0 <= 1: the
        # ideal, background-free floor rises toward 1 as N increases, and
        # 1 itself represents no correlation at all - as dilute as this
        # model can express. Any g2_0 > 1 makes n_emitters*(1-g2_0)
        # negative, which the max(0, ...) below would otherwise silently
        # clamp to a degenerate f_bg = 1.0 (100% background), a value that
        # doesn't reflect a real measurement. Excluding these files here
        # is more honest than reporting that degenerate value.
        return None, "bad_g2", g2_0, None

    val = max(0, n_emitters * (1 - g2_0))
    rho = np.sqrt(val)
    rho = min(max(rho, 0), 1)

    f_bg = 1 - rho

    return f_bg, method, g2_0, popt

# =========================================================
# FILE LOADING
# =========================================================
def get_iter_columns(df):
    """iter_ columns sorted by their numeric suffix (iter_1, iter_2, ...)."""
    cols = [c for c in df.columns if c.startswith("iter_")]
    return sorted(cols, key=lambda x: int(x.split("_")[1]))


def load_experimental_file(filepath):
    """
    Reads one real-acquisition file in the SAME multi-column format as the
    simulated g2_raw_rep_*.csv files and returns (tau, counts, raw_counts,
    baseline).

    Only the LAST iter_ column is used: iter_1..iter_K are nested, cumulative
    snapshots of the SAME acquisition (not independent repeats), so using
    every column as a separate "sample" would inflate the apparent sample
    size ~K-fold. Using only the longest-integration column guarantees
    exactly one independent data point per file.

    If Step_00 also wrote a companion "..._rawcounts.csv" file (same name,
    that suffix before .csv), it's loaded too - raw_counts is the last
    iteration's raw counts, and baseline is derived from the raw/
    normalized ratio (median over valid points, exact wherever normalized
    != 0). Both are None if no companion file is found, and
    extract_background_fraction falls back to unweighted fitting in that
    case.
    """
    df = pd.read_csv(filepath)
    tau = df["tau"].values

    iter_cols = get_iter_columns(df)
    if len(iter_cols) == 0:
        raise ValueError(f"no iter_ columns found in {filepath}")

    last_col = iter_cols[-1]
    counts = df[last_col].values

    raw_counts = None
    baseline = None
    rawcounts_path = re.sub(r"\.csv$", "_rawcounts.csv", filepath)
    if os.path.exists(rawcounts_path):
        raw_df = pd.read_csv(rawcounts_path)
        raw_last = raw_df[last_col].values
        with np.errstate(divide="ignore", invalid="ignore"):
            ratio = raw_last / counts
        valid = np.isfinite(ratio) & (counts != 0)
        if np.any(valid):
            raw_counts = raw_last
            baseline = float(np.median(ratio[valid]))

    return tau, counts, raw_counts, baseline

# =========================================================
# MAIN LOOP
# =========================================================
raw_results = {n: [] for n in range(1, 6)}          # per-N f_bg (unpooled, for reference)
raw_A2_results = {n: [] for n in range(1, 6)}        # per-N bunching pedestal A2 (unpooled, for reference)
all_values = []                                      # clean per-file output table

stats = {
    "total": 0,
    "kept": 0,
    "fit_used": 0,
    "direct_used": 0,
    "weighted_fit": 0,
    "unweighted_fit": 0,
    "bad_baseline": 0,
    "zero_baseline": 0,
    "bad_g2": 0,
    "unreadable": 0,
}

for file in sorted(os.listdir(FOLDER)):
    match = FILENAME_PATTERN.search(file)
    if not match:
        continue

    n_emitters = int(match.group(2))
    filepath = os.path.join(FOLDER, file)

    stats["total"] += 1

    try:
        tau, counts, raw_counts, baseline = load_experimental_file(filepath)
    except Exception as e:
        stats["unreadable"] += 1
        print(f"  [warn] could not read {file}: {e}")
        continue

    f_bg, status, g2_0, popt = extract_background_fraction(
        tau, counts, n_emitters, raw_counts=raw_counts, baseline=baseline
    )

    if f_bg is None:
        stats[status] += 1
        if PLOT_DEBUG:
            plt.figure()
            plt.plot(tau, counts)
            plt.title(f"Rejected: {file} ({status})")
            plt.close()
        continue

    stats["kept"] += 1
    if status == "fit":
        stats["fit_used"] += 1
    else:
        stats["direct_used"] += 1

    if raw_counts is not None and baseline is not None:
        stats["weighted_fit"] += 1
    else:
        stats["unweighted_fit"] += 1

    raw_results[n_emitters].append(f_bg)

    A2 = np.nan
    if popt is not None:
        _, _, A2 = popt
        raw_A2_results[n_emitters].append(A2)

    # Per-file output row. "tau2" is kept as a column (always NaN) purely
    # for backward format compatibility with any script expecting that
    # column - no meaningful tau2 can be extracted from this data at all
    # (see the MODEL section above). "A2" is the physically meaningful
    # quantity: a constant bunching pedestal.
    all_values.append([file, n_emitters, f_bg, np.nan, A2])

# =========================================================
# SUMMARY (reflects the ACTUAL pools the generation script will use)
# =========================================================
def summarize(vals):
    vals = np.array(vals)
    n = len(vals)
    if n == 0:
        return None
    low_confidence = n < MIN_SAMPLES_FOR_CONFIDENCE
    if low_confidence:
        # Percentile trimming is unreliable at small n (can exclude both
        # the min AND max, leaving only the median, which then falsely
        # reports std=0). Use raw mean/std/min-max instead.
        mean, std, low, high = np.mean(vals), np.std(vals), np.min(vals), np.max(vals)
    else:
        low = np.percentile(vals, 5)
        high = np.percentile(vals, 95)
        clipped = vals[(vals >= low) & (vals <= high)]
        mean, std = np.mean(clipped), np.std(clipped)
    return mean, std, low, high, n, low_confidence

summary_rows = []
print("\n=== Calibration statistics (pooled as used by the generation script) ===")

n1_f_bg = raw_results[1]
n1_A2 = raw_A2_results[1]
n2plus_f_bg = sum((raw_results[n] for n in [2, 3, 4, 5]), [])
n2plus_A2 = sum((raw_A2_results[n] for n in [2, 3, 4, 5]), [])

# Cascading fallback: if the N>=2 pool doesn't reach the confidence
# threshold even after pooling 2,3,4,5 together, blend in the N=1 data too
# rather than reporting (or bootstrapping from) an unreliable estimate
# built from a handful of points alone. This extends the exact same
# reasoning already used to justify pooling N=2..5 together in the first
# place - blending, not fully replacing, so whatever real N>=2 data exists
# is never discarded. Clearly flagged below whenever it actually triggers.
f_bg_used_fallback = len(n2plus_f_bg) < MIN_SAMPLES_FOR_CONFIDENCE
A2_used_fallback = len(n2plus_A2) < MIN_SAMPLES_FOR_CONFIDENCE

if f_bg_used_fallback:
    n2plus_f_bg = n2plus_f_bg + n1_f_bg
if A2_used_fallback:
    n2plus_A2 = n2plus_A2 + n1_A2

for n_key, label in [(1, "N=1"), (2, "N>=2 (pooled 2,3,4,5)")]:
    if n_key == 1:
        f_bg_pool = n1_f_bg
        A2_pool = n1_A2
        fbg_note = A2_note = ""
    else:
        f_bg_pool = n2plus_f_bg
        A2_pool = n2plus_A2
        fbg_note = " [blended with N=1 - see note above]" if f_bg_used_fallback else ""
        A2_note = " [blended with N=1 - see note above]" if A2_used_fallback else ""

    fbg_stats = summarize(f_bg_pool)
    A2_stats = summarize(A2_pool)

    print(f"\n{label}")
    if fbg_stats is None:
        print("  f_bg:  NO DATA")
        fbg_row = [np.nan]*6
    else:
        mean, std, low, high, n, lc = fbg_stats
        flag = "  *** LOW CONFIDENCE ***" if lc else ""
        print(f"  f_bg:  n={n}, mean={mean:.4f}, std={std:.4f}, range=[{low:.4f}, {high:.4f}]{flag}{fbg_note}")
        fbg_row = [mean, std, low, high, n, lc]

    if A2_stats is None:
        print("  A2:    NO DATA")
        A2_row = [np.nan]*6
    else:
        mean, std, low, high, n, lc = A2_stats
        flag = "  *** LOW CONFIDENCE ***" if lc else ""
        print(f"  A2:    n={n}, mean={mean:.4f}, std={std:.4f}, range=[{low:.4f}, {high:.4f}]{flag}{A2_note}"
              f"  (constant bunching pedestal - see MODEL note; not yet consumed downstream)")
        A2_row = [mean, std, low, high, n, lc]

    used_fallback_row = [f_bg_used_fallback if n_key != 1 else False,
                          A2_used_fallback if n_key != 1 else False]
    summary_rows.append([label] + fbg_row + A2_row + used_fallback_row)

# =========================================================
# SAVE FILES (only what's actually used downstream)
# =========================================================
# "tau2" column kept as NaN for backward format compatibility - see the
# note where it's populated above. "A2" is the meaningful bunching
# quantity, consumed by Step_02.
pd.DataFrame(all_values, columns=["file", "N", "f_bg", "tau2", "A2"]
             ).to_csv("experimental_calibration.csv", index=False)

pd.DataFrame(summary_rows, columns=[
    "pool",
    "f_bg_mean", "f_bg_std", "f_bg_low", "f_bg_high", "f_bg_n", "f_bg_low_confidence",
    "A2_mean", "A2_std", "A2_low", "A2_high", "A2_n", "A2_low_confidence",
    "f_bg_used_n1_fallback", "A2_used_n1_fallback",
]).to_csv("calibration_summary.csv", index=False)

# =========================================================
# DIAGNOSTICS
# =========================================================
print("\n=== Diagnostics ===")
for k, v in stats.items():
    print(f"{k}: {v}")